/**
 * The scale reference (FR-02).
 *
 * *Accept: scan payload contains `marker_type` and `marker_mm`; a scan cannot be submitted without
 * them.* That invariant has one choke point, `markerFieldsForScan`, and the tests below are what
 * stop it from being quietly widened later.
 *
 * The physical constants are pinned too. A wrong 40.0 or 85.6 does not throw, does not fail a
 * render and does not look like anything — it just multiplies every millimetre in every report by
 * a constant factor, and the reports still look entirely plausible.
 */

import type { MarkerType } from '@/domain';
import {
  ARUCO_SIDE_MM,
  ID1_LONG_EDGE_MM,
  ID1_SHORT_EDGE_MM,
  MARKER_SPECS,
  MarkerNotSetError,
  RECOMMENDED_MARKER_TYPE,
  USER_DIMENSION_MAX_MM,
  USER_DIMENSION_MIN_MM,
  buildReference,
  isMarkerReference,
  isValidUserDimension,
  markerFieldsForScan,
  specFor,
} from '@/features/capture';
import { ENFORCEMENT_ORG, INSPECTOR } from '@/api/mock/fixtures/orgs';
import { storage } from '@/lib/storage';
import { MARKER_STORAGE_KEY, useMarkerStore } from '@/store/marker';
import { useSession } from '@/store/session';

/**
 * Exhaustive by construction: adding a `MarkerType` without a spec stops this file compiling,
 * which is the point. A reference with no declared size would reach the backend as `undefined` mm.
 */
const ALL_MARKER_TYPES: Record<MarkerType, true> = {
  aruco_40mm: true,
  id1_card: true,
  user_dimension: true,
};

afterEach(() => {
  useMarkerStore.getState().clearReference();
});

describe('the physical constants', () => {
  it('matches the printed tag generated by scripts/make-marker-sheet.py', () => {
    // The sheet renders the tag at exactly 600 px on a 15 px/mm page. Change one, change both.
    expect(ARUCO_SIDE_MM).toBe(40.0);
  });

  it('matches ISO/IEC 7810 ID-1', () => {
    expect(ID1_LONG_EDGE_MM).toBe(85.6);
    expect(ID1_SHORT_EDGE_MM).toBe(53.98);
  });

  it('sends the long edge as markerMm, which is the larger of the two', () => {
    expect(ID1_LONG_EDGE_MM).toBeGreaterThan(ID1_SHORT_EDGE_MM);
    expect(specFor('id1_card').mm).toBe(ID1_LONG_EDGE_MM);
  });
});

describe('MARKER_SPECS', () => {
  it('covers every marker type the domain declares', () => {
    expect(MARKER_SPECS.map((s) => s.type).sort()).toEqual(Object.keys(ALL_MARKER_TYPES).sort());
  });

  it('ranks the printed tag first and recommends it', () => {
    const ranks = MARKER_SPECS.map((s) => s.rank);
    expect([...ranks].sort((a, b) => a - b)).toEqual(ranks);
    expect(MARKER_SPECS[0].type).toBe(RECOMMENDED_MARKER_TYPE);
    expect(specFor(RECOMMENDED_MARKER_TYPE).rank).toBe(0);
  });

  it('gives every fixed-size reference a positive size, and only the user one none', () => {
    for (const spec of MARKER_SPECS) {
      if (spec.type === 'user_dimension') {
        expect(spec.mm).toBeNull();
      } else {
        expect(spec.mm).toBeGreaterThan(0);
      }
    }
  });
});

describe('buildReference', () => {
  it('resolves the fixed references without asking the user anything', () => {
    expect(buildReference('aruco_40mm')).toEqual({ type: 'aruco_40mm', mm: ARUCO_SIDE_MM });
    expect(buildReference('id1_card')).toEqual({ type: 'id1_card', mm: ID1_LONG_EDGE_MM });
  });

  it('ignores a user-supplied size for a reference whose size is a fact', () => {
    // Nobody gets to declare that the printed 40 mm tag is 38 mm.
    expect(buildReference('aruco_40mm', 38)).toEqual({ type: 'aruco_40mm', mm: ARUCO_SIDE_MM });
  });

  it('needs a measurement for a user dimension, and refuses without one', () => {
    expect(buildReference('user_dimension')).toBeNull();
    expect(buildReference('user_dimension', 60)).toEqual({ type: 'user_dimension', mm: 60 });
  });

  it('rejects a user dimension outside the usable range', () => {
    expect(buildReference('user_dimension', USER_DIMENSION_MIN_MM - 0.1)).toBeNull();
    expect(buildReference('user_dimension', USER_DIMENSION_MAX_MM + 0.1)).toBeNull();
    expect(buildReference('user_dimension', 0)).toBeNull();
    expect(buildReference('user_dimension', -50)).toBeNull();
    expect(buildReference('user_dimension', Number.NaN)).toBeNull();
  });

  it('accepts the range boundaries themselves', () => {
    expect(isValidUserDimension(USER_DIMENSION_MIN_MM)).toBe(true);
    expect(isValidUserDimension(USER_DIMENSION_MAX_MM)).toBe(true);
  });
});

describe('isMarkerReference', () => {
  it('accepts what the app writes', () => {
    expect(isMarkerReference({ type: 'aruco_40mm', mm: 40 })).toBe(true);
  });

  it('rejects a shape an older build might have stored', () => {
    for (const value of [
      null,
      undefined,
      'aruco_40mm',
      {},
      { type: 'aruco_40mm' },
      { mm: 40 },
      { type: 'not_a_marker', mm: 40 },
      { type: 'aruco_40mm', mm: '40' },
      { type: 'aruco_40mm', mm: 0 },
      { type: 'aruco_40mm', mm: -40 },
      { type: 'aruco_40mm', mm: Number.NaN },
    ]) {
      expect(isMarkerReference(value)).toBe(false);
    }
  });
});

describe('markerFieldsForScan — the FR-02 invariant', () => {
  it('refuses to build scan fields without a reference', () => {
    expect(() => markerFieldsForScan(null)).toThrow(MarkerNotSetError);
  });

  it('produces both markerType and markerMm, never one without the other', () => {
    const fields = markerFieldsForScan({ type: 'id1_card', mm: ID1_LONG_EDGE_MM });

    expect(fields).toEqual({ markerType: 'id1_card', markerMm: ID1_LONG_EDGE_MM });
    expect(Object.keys(fields).sort()).toEqual(['markerMm', 'markerType']);
  });

  it.each(MARKER_SPECS.filter((s) => s.mm !== null))(
    'carries the declared size for $type',
    (spec) => {
      const reference = buildReference(spec.type);
      expect(markerFieldsForScan(reference).markerMm).toBe(spec.mm);
    }
  );
});

describe('the marker store', () => {
  it('starts with nothing set up, so the Scan screen offers setup', () => {
    expect(useMarkerStore.getState().reference).toBeNull();
  });

  it('records when the reference was verified, not just what it is', () => {
    useMarkerStore.getState().setVerifiedReference({ type: 'aruco_40mm', mm: 40 });

    const { reference, verifiedAt } = useMarkerStore.getState();
    expect(reference).toEqual({ type: 'aruco_40mm', mm: 40 });
    expect(verifiedAt).not.toBeNull();
  });

  it('persists, so a printed marker does not have to be re-confirmed every launch', () => {
    useMarkerStore.getState().setVerifiedReference({ type: 'id1_card', mm: ID1_LONG_EDGE_MM });

    const raw = storage.getItem(MARKER_STORAGE_KEY);
    expect(raw).not.toBeNull();
    expect(JSON.parse(raw as string)).toMatchObject({
      reference: { type: 'id1_card', mm: ID1_LONG_EDGE_MM },
    });
  });

  it('survives signing out — the paper in your hand is not part of the session', () => {
    useMarkerStore.getState().setVerifiedReference({ type: 'aruco_40mm', mm: 40 });

    useSession.getState().signIn({
      accessToken: 'a',
      refreshToken: 'r',
      user: INSPECTOR,
      org: ENFORCEMENT_ORG,
    });
    useSession.getState().signOut();

    expect(storage.getItem(MARKER_STORAGE_KEY)).not.toBeNull();
    expect(useMarkerStore.getState().reference).toEqual({ type: 'aruco_40mm', mm: 40 });
  });

  it('clears completely, leaving no half-set state behind', () => {
    useMarkerStore.getState().setVerifiedReference({ type: 'aruco_40mm', mm: 40 });
    useMarkerStore.getState().clearReference();

    expect(useMarkerStore.getState()).toMatchObject({ reference: null, verifiedAt: null });
    expect(storage.getItem(MARKER_STORAGE_KEY)).toBeNull();
  });
});
