"""Generate the sample PDF and DOCX the mock backend hands to the share sheet.

Stage 9's acceptance is that **both files share out of the app and open in an external viewer**
(FR-08). A mock that resolves with a plausible-looking URI proves nothing about that: the share
path only exists if real bytes reach a real viewer. So the fixtures are genuine files — a
hand-built PDF 1.4 and a real OOXML package — emitted here as base64 and written to disk by the
mock transport's `download`.

Two things are deliberately real rather than gestured at:

* **The annotated image is the actual label with the actual boxes.** The regions come from
  `make-sample-label.py`, imported rather than retyped, so a box in the sample report cannot
  disagree with a box in the app. FR-08's acceptance names the annotated image explicitly.
* **The hashes and rule pack version are read out of `hero-scan.ts`.** A sample report quoting a
  different findings hash from the one the evidence panel shows would be a fixture that teaches
  the wrong thing about the product's whole integrity claim. If the regex below stops matching,
  this script fails rather than emitting a lie.

The DOCX carries the findings as a real `<w:tbl>`, because FR-27's acceptance is that the table is
editable in Word and LibreOffice and not a picture of a table.

Deleted at Stage 13 with the rest of the mock.

    python3 scripts/make-sample-report.py
"""

from __future__ import annotations

import base64
import importlib.util
import re
import textwrap
import zipfile
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageDraw

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

HERO_TS = ROOT / "src" / "api" / "mock" / "fixtures" / "hero-scan.ts"
OUT_TS = ROOT / "src" / "api" / "mock" / "fixtures" / "report-files.ts"

# ---------------------------------------------------------------- source of truth


def load_label_module():
    """Import `make-sample-label.py` for its region geometry.

    The hyphen in the filename rules out a plain import. Running it also rewrites the PNG and
    `label.ts`, which is harmless: the script is deterministic, so the rewrite is byte-identical.
    Retyping the boxes here instead is the one thing that would let the sample report's overlay
    drift from the app's.
    """
    spec = importlib.util.spec_from_file_location("sample_label", HERE / "make-sample-label.py")
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def read_hero() -> dict[str, str]:
    """Pull the hashes and rule pack version out of the fixtures, or fail."""
    source = HERO_TS.read_text()

    findings = re.search(r"FINDINGS_SHA256 =\s*\n?\s*'([0-9a-f]{64})'", source)
    raw = re.search(r"kind: 'raw',.*?sha256: '([0-9a-f]{64})'", source, re.S)

    rules = (ROOT / "src" / "api" / "mock" / "fixtures" / "rules.ts").read_text()
    version = re.search(r"RULEPACK_VERSION = '([^']+)'", rules)

    assert findings, "findings hash not found in hero-scan.ts — fix the regex, do not guess"
    assert raw, "raw asset sha256 not found in hero-scan.ts — fix the regex, do not guess"
    assert version, "rulepack version not found in rules.ts"

    return {
        "findings_sha256": findings.group(1),
        "image_sha256": raw.group(1),
        "rulepack": version.group(1),
    }


# The findings table, mirroring `HERO_FINDINGS`. Kept short on purpose: this is a sample document,
# and its job is to prove a real table reaches a real viewer, not to duplicate the fixture set.
FINDINGS = [
    ("LM-MRP-INCLUSIVE-WORDING", "FAIL", "inclusive-of-taxes wording", "MRP Rs 249.00"),
    ("LM-9-LETTER-HEIGHT", "FAIL", "1.0 mm", "0.90 mm"),
    ("LM-9-QTY-CLEAR-SPACE", "BORDERLINE", "clear space kept free", "3.2 mm, band +/-1.0 mm"),
    ("LM-9-3-WIDTH", "NOT ASSESSABLE", ">= 1/3 of glyph height", "not measurable"),
    ("LM-9-2-TABLE1", "PASS", "4.0 mm", "4.60 mm"),
    ("LM-6-1-D-NET-QUANTITY", "PASS", "declared in a prescribed unit", "Net Wt. 1 kg"),
]

DISCLAIMER = (
    "Advisory only - not a certification. Anupalan gives a pre-audit opinion. It carries no "
    "legal force and does not replace a Legal Metrology inspection or professional advice."
)

SAMPLE_NOTE = (
    "SAMPLE - generated by the mock backend so the share path can be exercised before the real "
    "report service exists. Not a real inspection."
)

VERDICT_RGB = {
    "FAIL": (179, 38, 30),
    "BORDERLINE": (138, 97, 0),
    "NOT_ASSESSABLE": (92, 107, 115),
    "PASS": (27, 127, 75),
}

# Which verdict each annotated region carries, worst-first so a shared box shows the worst.
REGION_VERDICT = {
    "mrp": "FAIL",
    "fine_print": "FAIL",
    "qty_clear_space": "BORDERLINE",
    "net_quantity": "PASS",
    "common_name": "PASS",
    "mfg_month_year": "PASS",
    "manufacturer_name": "PASS",
    "consumer_care": "PASS",
}

# ---------------------------------------------------------------- annotated image


def annotated_jpeg(label, width: int = 460, quality: int = 45) -> tuple[bytes, int, int]:
    """The rectified label with every finding's box drawn on it, as a JPEG for /DCTDecode.

    JPEG rather than PNG because a hand-built PDF can carry JPEG bytes verbatim through
    /DCTDecode, with no Flate encoder to write. Downscaled hard: this is a fixture that ships
    inside the app bundle, and a full 1400 x 2000 frame would cost more than the feature.
    """
    png = ROOT / "assets" / "fixtures" / "rectified-label.png"
    image = Image.open(png).convert("RGB")

    draw = ImageDraw.Draw(image)
    for key, verdict in REGION_VERDICT.items():
        box = label.regions[key]["box"]
        draw.rectangle(
            [box["x"], box["y"], box["x"] + box["width"], box["y"] + box["height"]],
            outline=VERDICT_RGB[verdict],
            width=6,
        )

    scale = width / image.width
    image = image.resize((width, round(image.height * scale)), Image.LANCZOS)

    buffer = BytesIO()
    image.save(buffer, format="JPEG", quality=quality, optimize=True)
    return buffer.getvalue(), image.width, image.height


# ---------------------------------------------------------------- PDF


def pdf_escape(text: str) -> str:
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def build_pdf(meta: dict[str, str], jpeg: bytes, jw: int, jh: int) -> bytes:
    """A single-page PDF 1.4, assembled by hand.

    Written out rather than produced with a library because adding a PDF dependency to the mobile
    app's tooling to generate one fixture is a poor trade, and the format's cross-reference table is
    twenty lines of arithmetic.
    """
    page_w, page_h = 595, 842  # A4 at 72 dpi
    margin = 48

    # --- the content stream -------------------------------------------------
    img_w = 170
    img_h = round(img_w * jh / jw)
    img_x = page_w - margin - img_w
    img_y = page_h - margin - 34 - img_h

    out: list[str] = ["BT /F2 16 Tf", f"1 0 0 1 {margin} {page_h - margin - 16} Tm",
                      f"({pdf_escape('Anupalan compliance report')}) Tj", "ET"]

    out.append(f"q {img_w} 0 0 {img_h} {img_x} {img_y} cm /Im1 Do Q")

    y = page_h - margin - 46
    column = page_w - margin - img_w - margin - 12

    def text(line: str, font: str = "F1", size: int = 9, gap: int = 13) -> None:
        nonlocal y
        out.extend(["BT", f"/{font} {size} Tf", f"1 0 0 1 {margin} {y} Tm",
                    f"({pdf_escape(line)}) Tj", "ET"])
        y -= gap

    for line in textwrap.wrap(SAMPLE_NOTE, width=max(20, column // 5)):
        text(line, size=8, gap=11)
    y -= 6

    text("Scan", "F2", 10)
    text("Sampoorna Whole Wheat Atta, 1 kg")
    text("Captured 2026-09-11T09:42:18Z, Nadia")
    text(f"Rule pack {meta['rulepack']}")
    y -= 8

    text("Integrity", "F2", 10)
    text("Raw image SHA-256", "F2", 8, gap=11)
    text(meta["image_sha256"][:32], "F3", 8, gap=11)
    text(meta["image_sha256"][32:], "F3", 8, gap=13)
    text("Findings SHA-256", "F2", 8, gap=11)
    text(meta["findings_sha256"][:32], "F3", 8, gap=11)
    text(meta["findings_sha256"][32:], "F3", 8)
    y -= 10

    # --- findings table -----------------------------------------------------
    # Full width, so it starts below the annotated image whatever the text above it ran to. The
    # table's own columns are what must not be crowded: a report where "Observed" is overprinted by
    # a picture is a report nobody can read the measurement off.
    y = min(y, img_y - 20)

    text("Findings", "F2", 10)
    y -= 2

    cols = [margin, margin + 168, margin + 262, margin + 392]
    row_h = 15

    def row(cells: tuple[str, str, str, str], font: str = "F1", rgb: tuple | None = None) -> None:
        nonlocal y
        if rgb:
            r, g, b = (v / 255 for v in rgb)
            out.append(f"{r:.3f} {g:.3f} {b:.3f} rg")
        for x, cell in zip(cols, cells):
            out.extend(["BT", f"/{font} 8 Tf", f"1 0 0 1 {x} {y} Tm",
                        f"({pdf_escape(cell[:26])}) Tj", "ET"])
        if rgb:
            out.append("0 0 0 rg")
        y -= row_h

    out.append(f"0.5 w {margin} {y + 11} m {page_w - margin} {y + 11} l S")
    row(("Rule", "Verdict", "Required", "Observed"), "F2")
    out.append(f"0.5 w {margin} {y + 11} m {page_w - margin} {y + 11} l S")

    for rule, verdict, required, observed in FINDINGS:
        row((rule, verdict, required, observed), rgb=VERDICT_RGB[verdict.replace(" ", "_")])

    out.append(f"0.5 w {margin} {y + 11} m {page_w - margin} {y + 11} l S")
    y -= 10

    text("Four verdicts, and borderline is not a failure.", "F1", 8)
    y -= 14

    for line in textwrap.wrap(DISCLAIMER, width=96):
        text(line, size=8, gap=11)

    stream = "\n".join(out).encode("latin-1")

    # --- objects ------------------------------------------------------------
    objects: list[bytes] = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        (
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {page_w} {page_h}] "
            f"/Resources << /Font << /F1 5 0 R /F2 6 0 R /F3 7 0 R >> "
            f"/XObject << /Im1 8 0 R >> >> /Contents 4 0 R >>"
        ).encode("latin-1"),
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>",
        (
            f"<< /Type /XObject /Subtype /Image /Width {jw} /Height {jh} "
            f"/ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode "
            f"/Length {len(jpeg)} >>\nstream\n"
        ).encode("latin-1") + jpeg + b"\nendstream",
    ]

    body = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets: list[int] = []

    for index, payload in enumerate(objects, start=1):
        offsets.append(len(body))
        body += f"{index} 0 obj\n".encode() + payload + b"\nendobj\n"

    xref_at = len(body)
    body += f"xref\n0 {len(objects) + 1}\n".encode()
    body += b"0000000000 65535 f \n"
    for offset in offsets:
        body += f"{offset:010d} 00000 n \n".encode()

    body += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF\n"
    ).encode()

    return bytes(body)


# ---------------------------------------------------------------- DOCX


def xml_escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build_docx(meta: dict[str, str]) -> bytes:
    """A real OOXML package with the findings as a real table.

    FR-27's acceptance: *DOCX opens in Word and LibreOffice with the findings table editable as a
    real table, not an image.* So the table is `<w:tbl>`, and nothing here is a picture.
    """

    def para(text: str, *, bold=False, size=20, mono=False) -> str:
        fonts = '<w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/>' if mono else ""
        return (
            "<w:p><w:pPr><w:spacing w:after=\"60\"/></w:pPr><w:r><w:rPr>"
            f"{fonts}{'<w:b/>' if bold else ''}<w:sz w:val=\"{size}\"/>"
            f"</w:rPr><w:t xml:space=\"preserve\">{xml_escape(text)}</w:t></w:r></w:p>"
        )

    def cell(text: str, *, bold=False, colour: str | None = None) -> str:
        shade = f'<w:color w:val="{colour}"/>' if colour else ""
        return (
            '<w:tc><w:tcPr><w:tcW w:w="2300" w:type="dxa"/></w:tcPr>'
            "<w:p><w:r><w:rPr>"
            f"{'<w:b/>' if bold else ''}{shade}<w:sz w:val=\"16\"/>"
            f"</w:rPr><w:t xml:space=\"preserve\">{xml_escape(text)}</w:t></w:r></w:p></w:tc>"
        )

    rows = [
        "<w:tr>"
        + cell("Rule", bold=True)
        + cell("Verdict", bold=True)
        + cell("Required", bold=True)
        + cell("Observed", bold=True)
        + "</w:tr>"
    ]
    for rule, verdict, required, observed in FINDINGS:
        hexed = "%02X%02X%02X" % VERDICT_RGB[verdict.replace(" ", "_")]
        rows.append(
            "<w:tr>"
            + cell(rule)
            + cell(verdict, bold=True, colour=hexed)
            + cell(required)
            + cell(observed)
            + "</w:tr>"
        )

    table = (
        '<w:tbl><w:tblPr><w:tblW w:w="9200" w:type="dxa"/>'
        '<w:tblBorders>'
        + "".join(
            f'<w:{edge} w:val="single" w:sz="4" w:color="CCCCCC"/>'
            for edge in ("top", "left", "bottom", "right", "insideH", "insideV")
        )
        + "</w:tblBorders></w:tblPr>"
        + "".join(rows)
        + "</w:tbl>"
    )

    document = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        "<w:body>"
        + para("Anupalan compliance report", bold=True, size=32)
        + para(SAMPLE_NOTE, size=16)
        + para("Scan", bold=True, size=24)
        + para("Sampoorna Whole Wheat Atta, 1 kg")
        + para("Captured 2026-09-11T09:42:18Z, Nadia")
        + para(f"Rule pack {meta['rulepack']}")
        + para("Integrity", bold=True, size=24)
        + para("Raw image SHA-256", bold=True, size=16)
        + para(meta["image_sha256"], size=16, mono=True)
        + para("Findings SHA-256", bold=True, size=16)
        + para(meta["findings_sha256"], size=16, mono=True)
        + para("Findings", bold=True, size=24)
        + table
        + para("Four verdicts, and borderline is not a failure.", size=16)
        + para(DISCLAIMER, size=16)
        + '<w:sectPr><w:pgSz w:w="11906" w:h="16838"/></w:sectPr>'
        "</w:body></w:document>"
    )

    content_types = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
        "</Types>"
    )

    rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
        "</Relationships>"
    )

    buffer = BytesIO()
    # A fixed date so a regenerated fixture is byte-identical and does not show up as a diff.
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, payload in (
            ("[Content_Types].xml", content_types),
            ("_rels/.rels", rels),
            ("word/document.xml", document),
        ):
            info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info, payload)

    return buffer.getvalue()


# ---------------------------------------------------------------- emit


def chunked(value: str, width: int = 96) -> str:
    lines = [value[i : i + width] for i in range(0, len(value), width)]
    return "\n".join(f"  '{line}' +" for line in lines[:-1]) + f"\n  '{lines[-1]}';"


def main() -> None:
    label = load_label_module()
    meta = read_hero()

    jpeg, jw, jh = annotated_jpeg(label)
    pdf = build_pdf(meta, jpeg, jw, jh)
    docx = build_docx(meta)

    header = f'''/**
 * The sample report files the mock backend writes to disk.
 *
 * GENERATED — do not edit by hand. Regenerate with:
 *
 *     python3 scripts/make-sample-report.py
 *
 * Stage 9's acceptance is that both files **share out of the app and open in an external viewer**
 * (FR-08), which a mock that resolves with a plausible URI cannot demonstrate. These are real
 * bytes: a PDF 1.4 carrying the annotated label, the findings table and both hashes, and an OOXML
 * package whose findings table is a real `<w:tbl>` and not a picture of one (FR-27).
 *
 * Base64 because the alternative is bundling binaries, which needs a `metro.config.js` asset
 * extension and approval (flag 13). `File.write(..., {{ encoding: 'base64' }})` decodes natively, so
 * nothing here is decoded in JS.
 *
 * The hashes inside both documents are read out of `hero-scan.ts` by the generator, so a sample
 * report cannot quote a different findings hash from the one the evidence panel shows.
 *
 * Deleted at Stage 13 with the rest of the mock.
 */

export const SAMPLE_PDF_BYTES = {len(pdf)};
export const SAMPLE_DOCX_BYTES = {len(docx)};

'''

    body = header
    body += "export const SAMPLE_PDF_BASE64 =\n"
    body += chunked(base64.b64encode(pdf).decode()) + "\n\n"
    body += "export const SAMPLE_DOCX_BASE64 =\n"
    body += chunked(base64.b64encode(docx).decode()) + "\n"

    OUT_TS.write_text(body)

    print(f"annotated image {jw}x{jh}, {len(jpeg) // 1024} KB jpeg")
    print(f"pdf  {len(pdf):>7} bytes -> {len(pdf) * 4 // 3:>7} base64")
    print(f"docx {len(docx):>7} bytes -> {len(docx) * 4 // 3:>7} base64")
    print(f"wrote {OUT_TS.relative_to(ROOT)} ({OUT_TS.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
