"""Initial schema — every table in docs/01-architecture.md §8, plus three it does not have.

Revision ID: 0001
Revises:
Create Date: 2026-09-12

Reviewed before it was written (CLAUDE.md §7, backend plan B12). The proposal and the nine
approved deviations from §8 are recorded in docs/decisions.md, 2026-09-12; §8 itself has been
updated to match, so this migration and the architecture document agree.

Three things in here are not autogenerated and must survive any regeneration:

* ``CREATE EXTENSION vector`` runs first. Nothing below it can be created without it.
* The HNSW index on ``bis_chunks.embedding`` is built **now, while the table is empty**. Adding
  it later against a populated corpus takes a lock (B12 card).
* Every index B17's dashboards need is here for the same reason — ``findings(scan_id)``,
  ``findings(rule_id, verdict)``, ``scans(org_id, captured_at)``, ``extractions(scan_id,
  field_code)``.

Run against ``DATABASE_URL_DIRECT``, Neon's non-pooled endpoint. The pooled endpoint is pgbouncer
in transaction mode and cannot run DDL reliably inside a transaction (CLAUDE.md §8);
``alembic/env.py`` selects the direct URL on its own, so there is nothing to remember here.
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the schema."""
    # pgvector backs bis_chunks.embedding and the HNSW index below. Neon offers it as an
    # extension; creating it is idempotent, so a re-run on a database that already has it is
    # a no-op rather than an error.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bis_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('qco_gazette', 'mandatory_cert_list', 'crs_list', 'scheme_guide', 'faq', 'hallmarking', 'lab_directory', 'catalogue_metadata')", name='ck_bis_documents_source_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('orgs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('enforcement', 'industry')", name='ck_orgs_mode'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_otp_requests_attempts_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_requests_phone_created', 'otp_requests', ['phone', 'created_at'], unique=False)
    op.create_table('bis_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(pgvector.sqlalchemy.vector.VECTOR(dim=1024), 'postgresql'), nullable=True),
    sa.Column('section_ref', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['bis_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bis_chunks_document', 'bis_chunks', ['document_id'], unique=False)
    op.create_index('ix_bis_chunks_embedding_hnsw', 'bis_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=True),
    sa.Column('gtin', sa.String(length=20), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('pack_type', sa.String(length=20), nullable=True),
    sa.Column('surface', sa.String(length=20), nullable=False),
    sa.Column('net_qty_value', sa.Double(), nullable=True),
    sa.Column('net_qty_unit', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pack_type IN ('rigid', 'flexible', 'glass', 'can', 'other')", name='ck_products_pack_type'),
    sa.CheckConstraint("surface IN ('printed', 'embossed', 'blown', 'formed', 'moulded', 'molded', 'perforated')", name='ck_products_surface'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_org_category', 'products', ['org_id', 'category_code'], unique=False)
    op.create_index('ix_products_org_gtin', 'products', ['org_id', 'gtin'], unique=False)
    op.create_index(op.f('ix_products_org_id'), 'products', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'inspector', 'analyst', 'viewer')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index('ix_audit_log_org_id_seq', 'audit_log', ['org_id', 'id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replaced_by'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_family', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('ix_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('rulepacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_rulepacks_code_version')
    )
    op.create_table('scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geo_lat', sa.Double(), nullable=True),
    sa.Column('geo_lon', sa.Double(), nullable=True),
    sa.Column('geo_accuracy_m', sa.Double(), nullable=True),
    sa.Column('device_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('marker_type', sa.String(length=30), nullable=False),
    sa.Column('marker_mm', sa.Double(), nullable=False),
    sa.Column('profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("marker_type IN ('aruco_4x4_50', 'id1_card', 'user_declared')", name='ck_scans_marker_type'),
    sa.CheckConstraint("status IN ('created', 'queued', 'processing', 'complete', 'failed', 'no_marker')", name='ck_scans_status'),
    sa.CheckConstraint('marker_mm > 0', name='ck_scans_marker_mm_positive'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'org_id', name='uq_scans_id_org')
    )
    op.create_index('ix_scans_org_captured', 'scans', ['org_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_scans_org_id'), 'scans', ['org_id'], unique=False)
    op.create_index('ix_scans_org_status', 'scans', ['org_id', 'status'], unique=False)
    op.create_table('bis_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('citations_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bis_queries_org_created', 'bis_queries', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bis_queries_org_id'), 'bis_queries', ['org_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('field_code', sa.String(length=50), nullable=False),
    sa.Column('value_raw', sa.Text(), nullable=False),
    sa.Column('value_norm', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('bbox_x', sa.Double(), nullable=True),
    sa.Column('bbox_y', sa.Double(), nullable=True),
    sa.Column('bbox_w', sa.Double(), nullable=True),
    sa.Column('bbox_h', sa.Double(), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('regex', 'llm', 'human')", name='ck_extractions_source'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scan_id', 'org_id'], ['scans.id', 'scans.org_id'], name='fk_extractions_scan_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by'], ['extractions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_org_id'), 'extractions', ['org_id'], unique=False)
    op.create_index('ix_extractions_scan_field', 'extractions', ['scan_id', 'field_code'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('field_code', sa.String(length=50), nullable=False),
    sa.Column('glyph', sa.String(length=8), nullable=True),
    sa.Column('height_mm', sa.Double(), nullable=True),
    sa.Column('width_mm', sa.Double(), nullable=True),
    sa.Column('uncertainty_mm', sa.Double(), nullable=True),
    sa.Column('clear_space_mm', sa.Double(), nullable=True),
    sa.Column('is_numeral', sa.Boolean(), nullable=False),
    sa.Column('is_mark', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scan_id', 'org_id'], ['scans.id', 'scans.org_id'], name='fk_measurements_scan_org', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_org_id'), 'measurements', ['org_id'], unique=False)
    op.create_index('ix_measurements_scan_field', 'measurements', ['scan_id', 'field_code'], unique=False)
    op.create_table('scan_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('px_per_mm', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('raw', 'rectified', 'annotated')", name='ck_scan_assets_kind'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scan_id', 'org_id'], ['scans.id', 'scans.org_id'], name='fk_scan_assets_scan_org', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_scan_assets_org_id'), 'scan_assets', ['org_id'], unique=False)
    op.create_index('ix_scan_assets_scan_kind', 'scan_assets', ['scan_id', 'kind'], unique=False)
    op.create_table('scan_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('rulepack_version', sa.String(length=50), nullable=False),
    sa.Column('rulepack_checksum', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('findings_sha256', sa.String(length=64), nullable=False),
    sa.Column('reduced_extraction', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('pipeline', 'confirm_fields', 'admin_recompute')", name='ck_scan_evaluations_source'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scan_id', 'org_id'], ['scans.id', 'scans.org_id'], name='fk_scan_evaluations_scan_org', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'revision', name='uq_scan_evaluations_scan_revision')
    )
    op.create_index(op.f('ix_scan_evaluations_org_id'), 'scan_evaluations', ['org_id'], unique=False)
    op.create_index('ix_scan_evaluations_scan', 'scan_evaluations', ['scan_id', 'revision'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('rulepack_version', sa.String(length=50), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('observed', sa.Text(), nullable=True),
    sa.Column('required', sa.Text(), nullable=True),
    sa.Column('observed_value', sa.Double(), nullable=True),
    sa.Column('required_value', sa.Double(), nullable=True),
    sa.Column('band', sa.String(length=50), nullable=True),
    sa.Column('field_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('bbox_x', sa.Double(), nullable=True),
    sa.Column('bbox_y', sa.Double(), nullable=True),
    sa.Column('bbox_w', sa.Double(), nullable=True),
    sa.Column('bbox_h', sa.Double(), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verdict IN ('PASS', 'FAIL', 'BORDERLINE', 'NOT_ASSESSABLE')", name='ck_findings_verdict'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['scan_evaluations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scan_id', 'org_id'], ['scans.id', 'scans.org_id'], name='fk_findings_scan_org', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_evaluation', 'findings', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_findings_org_id'), 'findings', ['org_id'], unique=False)
    op.create_index('ix_findings_rule_verdict', 'findings', ['rule_id', 'verdict'], unique=False)
    op.create_index('ix_findings_scan', 'findings', ['scan_id'], unique=False)
    op.create_table('ocr_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('raw_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mean_conf', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['scan_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scan_id', 'org_id'], ['scans.id', 'scans.org_id'], name='fk_ocr_results_scan_org', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_results_org_id'), 'ocr_results', ['org_id'], unique=False)
    op.create_index('ix_ocr_results_scan', 'ocr_results', ['scan_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('pdf_key', sa.String(length=500), nullable=True),
    sa.Column('docx_key', sa.String(length=500), nullable=True),
    sa.Column('json_key', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['scan_evaluations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scan_id', 'org_id'], ['scans.id', 'scans.org_id'], name='fk_reports_scan_org', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_org_id'), 'reports', ['org_id'], unique=False)
    op.create_index('ix_reports_scan', 'reports', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the schema.

    The ``vector`` extension is deliberately left in place: it is database-wide, another schema
    may be using it, and dropping an extension out from under someone else's table is not this
    migration's business.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_scan', table_name='reports')
    op.drop_index(op.f('ix_reports_org_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_ocr_results_scan', table_name='ocr_results')
    op.drop_index(op.f('ix_ocr_results_org_id'), table_name='ocr_results')
    op.drop_table('ocr_results')
    op.drop_index('ix_findings_scan', table_name='findings')
    op.drop_index('ix_findings_rule_verdict', table_name='findings')
    op.drop_index(op.f('ix_findings_org_id'), table_name='findings')
    op.drop_index('ix_findings_evaluation', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_scan_evaluations_scan', table_name='scan_evaluations')
    op.drop_index(op.f('ix_scan_evaluations_org_id'), table_name='scan_evaluations')
    op.drop_table('scan_evaluations')
    op.drop_index('ix_scan_assets_scan_kind', table_name='scan_assets')
    op.drop_index(op.f('ix_scan_assets_org_id'), table_name='scan_assets')
    op.drop_table('scan_assets')
    op.drop_index('ix_measurements_scan_field', table_name='measurements')
    op.drop_index(op.f('ix_measurements_org_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index('ix_extractions_scan_field', table_name='extractions')
    op.drop_index(op.f('ix_extractions_org_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_bis_queries_org_id'), table_name='bis_queries')
    op.drop_index('ix_bis_queries_org_created', table_name='bis_queries')
    op.drop_table('bis_queries')
    op.drop_index('ix_scans_org_status', table_name='scans')
    op.drop_index(op.f('ix_scans_org_id'), table_name='scans')
    op.drop_index('ix_scans_org_captured', table_name='scans')
    op.drop_table('scans')
    op.drop_table('rulepacks')
    op.drop_index('ix_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_audit_log_org_id_seq', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_org_id'), table_name='products')
    op.drop_index('ix_products_org_gtin', table_name='products')
    op.drop_index('ix_products_org_category', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_bis_chunks_embedding_hnsw', table_name='bis_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_bis_chunks_document', table_name='bis_chunks')
    op.drop_table('bis_chunks')
    op.drop_index('ix_otp_requests_phone_created', table_name='otp_requests')
    op.drop_table('otp_requests')
    op.drop_table('orgs')
    op.drop_table('bis_documents')
    # ### end Alembic commands ###
