"""Idempotency records for creating POSTs (B14).

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-12

Reviewed before it was written (CLAUDE.md §7). The mobile app retries on a flaky connection and,
with FR-04's offline queue, may retry a scan submitted days earlier — so a request arriving twice
is the normal case. Without this table every retry is a second scan: duplicate evidence, duplicate
findings, and a dashboard that counts one inspection twice.

Run against ``DATABASE_URL_DIRECT``, like every migration here.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the idempotency table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('response_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'endpoint', 'key', name='uq_idempotency_org_endpoint_key')
    )
    op.create_index('ix_idempotency_keys_created', 'idempotency_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_org_id'), 'idempotency_keys', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop it."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idempotency_keys_org_id'), table_name='idempotency_keys')
    op.drop_index('ix_idempotency_keys_created', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
