/**
 * Scale references: what the app will measure millimetres against (FR-02).
 *
 * Every metric rule in the pack is a millimetre comparison, and a millimetre is only knowable
 * because something of a **known physical size** is in the same photograph. That is the whole
 * reason the marker exists (`01-architecture.md` §5 S3). No reference means no millimetres, and
 * the honest answer is NOT_ASSESSABLE — never an estimate (CLAUDE.md §3.3).
 *
 * Three references, in descending order of trust (`01-architecture.md` §9):
 *
 * | Reference | Size | Why this rank |
 * |---|---|---|
 * | Printed ArUco tag | 40.00 mm | Self-identifying and self-orienting: the detector recovers all four corners, so it gives the homography as well as the scale. |
 * | ID-1 card | 85.60 mm long edge | Exact by ISO/IEC 7810 and in everyone's pocket, but plain — corner detection is on a blank rectangle, so it is less robust. |
 * | Known pack dimension | user-entered | Last resort. Depends on the user measuring correctly, and on the dimension lying in the label's plane. |
 *
 * The numbers live here rather than in a screen because they are physical constants, and a
 * hardcoded `40` at a call site is the same class of mistake as a hardcoded `20` for `PX_PER_MM`
 * (CLAUDE.md §8).
 */

import type { MarkerType } from '@/domain';

/** The printed tag: ArUco 4x4_50, id 0, generated by `scripts/make-marker-sheet.py`. */
export const ARUCO_SIDE_MM = 40.0;

/** ISO/IEC 7810 ID-1. The long edge is what `markerMm` carries. */
export const ID1_LONG_EDGE_MM = 85.6;
export const ID1_SHORT_EDGE_MM = 53.98;

/**
 * Bounds on a user-entered dimension.
 *
 * Below 20 mm a half-millimetre error reading a ruler is already 2.5% of the scale, and that error
 * multiplies into every measurement on the pack — a 4.0 mm threshold judged against a 3.9 mm
 * observation is the difference between PASS and FAIL. Above 200 mm the reference and the label
 * cannot both be in frame at a resolution that leaves glyph heights measurable.
 */
export const USER_DIMENSION_MIN_MM = 20;
export const USER_DIMENSION_MAX_MM = 200;

export interface MarkerSpec {
  type: MarkerType;
  /** The value sent as `markerMm`, or null where the user supplies it. */
  mm: number | null;
  /** Lower is more trustworthy. Orders the choices and picks the recommended one. */
  rank: number;
}

export const MARKER_SPECS: readonly MarkerSpec[] = [
  { type: 'aruco_40mm', mm: ARUCO_SIDE_MM, rank: 0 },
  { type: 'id1_card', mm: ID1_LONG_EDGE_MM, rank: 1 },
  { type: 'user_dimension', mm: null, rank: 2 },
];

export const RECOMMENDED_MARKER_TYPE: MarkerType = 'aruco_40mm';

export function specFor(type: MarkerType): MarkerSpec {
  const spec = MARKER_SPECS.find((s) => s.type === type);
  if (!spec) throw new Error(`No marker spec for ${type}`);
  return spec;
}

/** A chosen reference, with its size resolved to a single number. */
export interface MarkerReference {
  type: MarkerType;
  mm: number;
}

export function isValidUserDimension(mm: number): boolean {
  return Number.isFinite(mm) && mm >= USER_DIMENSION_MIN_MM && mm <= USER_DIMENSION_MAX_MM;
}

/**
 * Build a reference from a choice, or `null` if the choice is not yet complete or not valid.
 *
 * `userMm` is ignored for the fixed-size references: a user cannot talk the app into believing
 * their printed tag is 38 mm, because the tag's size is a property of the sheet, not a preference.
 */
export function buildReference(type: MarkerType, userMm?: number): MarkerReference | null {
  const spec = specFor(type);

  if (spec.mm !== null) return { type, mm: spec.mm };
  if (userMm === undefined || !isValidUserDimension(userMm)) return null;

  return { type, mm: userMm };
}

export function isMarkerReference(value: unknown): value is MarkerReference {
  if (typeof value !== 'object' || value === null) return false;

  const { type, mm } = value as { type?: unknown; mm?: unknown };
  if (typeof mm !== 'number' || !Number.isFinite(mm) || mm <= 0) return false;
  if (typeof type !== 'string') return false;

  return MARKER_SPECS.some((spec) => spec.type === type);
}

/** Thrown where a scan is assembled without a reference. See `markerFieldsForScan`. */
export class MarkerNotSetError extends Error {
  constructor() {
    super('No scale reference has been set up');
    this.name = 'MarkerNotSetError';
  }
}

/**
 * **The FR-02 invariant, in one place:** a scan carries `markerType` and `markerMm`, or it is not
 * created at all.
 *
 * The UI prevents this from ever throwing — the capture entry point is disabled until a reference
 * is set up. That is the friendly half. This is the half that holds if a future screen forgets,
 * because a scan submitted without a declared reference is one whose millimetres cannot be
 * reproduced, and it would fail silently: every metric rule NOT_ASSESSABLE, no error anywhere.
 */
export function markerFieldsForScan(reference: MarkerReference | null): {
  markerType: MarkerType;
  markerMm: number;
} {
  if (!reference) throw new MarkerNotSetError();

  return { markerType: reference.type, markerMm: reference.mm };
}
